"""add indexes and unique constraints

Revision ID: 455a2bb9cb91
Revises: e4191fba2873
Create Date: 2026-02-24 22:27:49.430956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455a2bb9cb91'
down_revision: Union[str, Sequence[str], None] = 'e4191fba2873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_habit_logs_habit_date', 'habit_logs', ['habit_id', 'date'])
    op.create_index('ix_habit_logs_user_date', 'habit_logs', ['user_id', 'date'])
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        with op.batch_alter_table("habit_logs") as batch_op:
            batch_op.create_unique_constraint(
                "uq_user_habit_date",
                ["user_id", "habit_id","date"]
            )
    else:
        op.create_unique_constraint(
                "uq_user_habit_date",
                "habit_logs",
                ["user_id", "habit_id","date"]
            )
    op.create_index('ix_habits_user_archived', 'habits', ['user_id', 'is_archived'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_habits_user_archived', table_name='habits')
    op.drop_constraint('uq_user_habit_date', 'habit_logs', type_='unique')
    op.drop_index('ix_habit_logs_user_date', table_name='habit_logs')
    op.drop_index('ix_habit_logs_habit_date', table_name='habit_logs')
    # ### end Alembic commands ###
